format_version: v1.0
type: UniqueComponent
attributes: {id: i2c4}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c4, value: '242'}
  - type: Integer
    attributes: {id: I2CS_CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c4, value: '100000000'}
  - type: Integer
    attributes: {id: I2CS_RISE_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c4, value: '30'}
  - type: Integer
    attributes: {id: I2CS_SETUP_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c4, value: '10'}
  - type: Integer
    attributes: {id: I2C_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c4, value: '100000000'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '200000'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c4, value: '200000'}
- type: ElementPosition
  attributes: {x: '243', y: '86', id: i2c4}
